import "./globals.css"
import type { Metadata } from "next"
import React from "react"
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={"transition-colors w-full h-full"} suppressHydrationWarning>
            <body className={"w-full h-full transition-colors"}>
                {/*This is just so tailwind keeps the dark class.*/}
                <div className={"light dark"} hidden></div>
                <ThemeProvider storageKey="theme" attribute="class" defaultTheme="system" enableSystem>
                    <main className={"w-full h-full"}>{children}</main>
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    )
}
